"""SVDQuant W4A4 algorithm building blocks."""

from comfy_quants.algorithms.int4_svdquant.config import (
    CALIBRATED_SVDQUANT_MODE,
    EXPERIMENTAL_SMOOTH_RTN_SVD_NO_GPTQ_STATE,
    EXPERIMENTAL_SVDQUANT_GPTQ_AWQ_RUNTIME_UNVERIFIED_STATE,
    EXPERIMENTAL_SVDQUANT_GPTQ_NO_AWQ_STATE,
    GPTQ_STATE_LAYER_CORE_INTEGRATED,
    GPTQ_STATE_NOT_IMPLEMENTED,
    MIXED_QUANTIZATION_SVD_AWQ_EXPERIMENTAL_STATE,
    MIXED_QUANTIZATION_SVD_ONLY_STATE,
    PUBLISHABLE_SVDQUANT_GPTQ_STATE,
    RUNTIME_CONTRACT_STATIC_ARTIFACT_ONLY,
    SVDQUANT_GPTQ_EXPERIMENTAL_MODE,
    SUPPORTED_QUANTIZATION_MODES,
    WEIGHT_ONLY_MODE,
    WEIGHT_ONLY_INITIALIZATION_STATE,
    Int4SvdquantPipelineConfig,
    algorithm_notes_for_quantization_mode,
    algorithm_state_for_quantization_mode,
    is_publishable_svdquant_gptq_state,
)
from comfy_quants.algorithms.int4_svdquant.branch_basis import (
    fold_proj_down_for_raw_branch,
    unfold_proj_down_for_post_smoothing_branch,
)
from comfy_quants.algorithms.int4_svdquant.calibration import (
    ActivationSampleRef,
    ActivationStatsAccumulator,
    load_activation_sample_refs,
    reduce_activation_samples_from_safetensors,
    summarize_activation_stats_map,
)
from comfy_quants.algorithms.int4_svdquant.gptq import (
    GptqConfig,
    GptqHessianStats,
    GptqInt4WeightQuantization,
    build_gptq_hessian_from_activations,
    quantize_linear_weight_grouped_signed_int4_gptq,
    transform_gptq_hessian_input_basis,
)

from comfy_quants.algorithms.int4_svdquant.hessian import (
    DEFAULT_GPTQ_HESSIAN_MANIFEST,
    DEFAULT_GPTQ_HESSIAN_TENSOR_DIR,
    GPTQ_HESSIAN_REDUCE_REPORT_SCHEMA_VERSION,
    GPTQ_HESSIAN_STATS_SCHEMA_VERSION,
    GptqHessianLayerRecord,
    GptqHessianReduceReport,
    load_gptq_hessian_manifest,
    load_gptq_hessian_tensor,
    reduce_gptq_hessians_from_safetensors,
    resolve_gptq_hessian_tensor_path,
)
from comfy_quants.algorithms.int4_svdquant.lowrank import (
    LowRankBranch,
    solve_lowrank_output_error_branch,
    solve_lowrank_residual_branch,
)
from comfy_quants.algorithms.int4_svdquant.reference import (
    SVDQUANT_W4A4_REFERENCE_STATE,
    dequantize_svdquant_w4a4_effective_weight,
    reference_svdquant_w4a4_linear,
)
from comfy_quants.algorithms.int4_svdquant.runtime_reference import (
    GELU_UNSIGNED_SHIFT,
    SVDQUANT_W4A4_RUNTIME_REFERENCE_STATE,
    ActivationW4Quantization,
    quantize_activation_w4_signed,
    quantize_activation_w4_unsigned,
    reference_svdquant_w4a4_linear_runtime,
)
from comfy_quants.algorithms.int4_svdquant.runtime_fixture import (
    DEFAULT_RUNTIME_FIXTURE_FILENAME,
    DEFAULT_RUNTIME_FIXTURE_REPORT_FILENAME,
    RUNTIME_FIXTURE_ARTIFACT_STATE,
    SVDQUANT_W4A4_RUNTIME_FIXTURE_SCHEMA_VERSION,
    SVDQuantW4A4RuntimeFixture,
    SVDQuantW4A4RuntimeFixtureConfig,
    WrittenSVDQuantW4A4RuntimeFixture,
    build_svdquant_w4a4_runtime_fixture,
    write_svdquant_w4a4_runtime_fixture,
)
from comfy_quants.algorithms.int4_svdquant.smoothing import SmoothResult, solve_smooth_factor
from comfy_quants.algorithms.int4_svdquant.stats import ActivationStats, activation_amax_from_samples, merge_activation_stats
from comfy_quants.algorithms.int4_svdquant.weight_quant import (
    dequantize_natural_svdquant_weight,
    quantize_linear_weight_to_calibrated_natural_svdquant,
    quantize_linear_weight_to_gptq_natural_svdquant,
    quantize_linear_weight_to_natural_svdquant,
)

__all__ = [
    "ActivationStats",
    "ActivationSampleRef",
    "ActivationStatsAccumulator",
    "CALIBRATED_SVDQUANT_MODE",
    "EXPERIMENTAL_SMOOTH_RTN_SVD_NO_GPTQ_STATE",
    "EXPERIMENTAL_SVDQUANT_GPTQ_AWQ_RUNTIME_UNVERIFIED_STATE",
    "EXPERIMENTAL_SVDQUANT_GPTQ_NO_AWQ_STATE",
    "GPTQ_STATE_LAYER_CORE_INTEGRATED",
    "GPTQ_STATE_NOT_IMPLEMENTED",
    "GELU_UNSIGNED_SHIFT",
    "reduce_gptq_hessians_from_safetensors",
    "load_gptq_hessian_manifest",
    "load_gptq_hessian_tensor",
    "resolve_gptq_hessian_tensor_path",
    "GptqHessianReduceReport",
    "GptqHessianLayerRecord",
    "GPTQ_HESSIAN_STATS_SCHEMA_VERSION",
    "GPTQ_HESSIAN_REDUCE_REPORT_SCHEMA_VERSION",
    "DEFAULT_GPTQ_HESSIAN_TENSOR_DIR",
    "DEFAULT_GPTQ_HESSIAN_MANIFEST",
    "GptqConfig",
    "GptqHessianStats",
    "GptqInt4WeightQuantization",
    "Int4SvdquantPipelineConfig",
    "LowRankBranch",
    "MIXED_QUANTIZATION_SVD_AWQ_EXPERIMENTAL_STATE",
    "MIXED_QUANTIZATION_SVD_ONLY_STATE",
    "PUBLISHABLE_SVDQUANT_GPTQ_STATE",
    "RUNTIME_CONTRACT_STATIC_ARTIFACT_ONLY",
    "SVDQUANT_W4A4_REFERENCE_STATE",
    "SVDQUANT_W4A4_RUNTIME_REFERENCE_STATE",
    "SVDQUANT_GPTQ_EXPERIMENTAL_MODE",
    "SUPPORTED_QUANTIZATION_MODES",
    "ActivationW4Quantization",
    "write_svdquant_w4a4_runtime_fixture",
    "build_svdquant_w4a4_runtime_fixture",
    "WrittenSVDQuantW4A4RuntimeFixture",
    "SVDQuantW4A4RuntimeFixtureConfig",
    "SVDQuantW4A4RuntimeFixture",
    "SVDQUANT_W4A4_RUNTIME_FIXTURE_SCHEMA_VERSION",
    "RUNTIME_FIXTURE_ARTIFACT_STATE",
    "DEFAULT_RUNTIME_FIXTURE_REPORT_FILENAME",
    "DEFAULT_RUNTIME_FIXTURE_FILENAME",
    "SmoothResult",
    "WEIGHT_ONLY_MODE",
    "WEIGHT_ONLY_INITIALIZATION_STATE",
    "activation_amax_from_samples",
    "algorithm_notes_for_quantization_mode",
    "algorithm_state_for_quantization_mode",
    "build_gptq_hessian_from_activations",
    "dequantize_natural_svdquant_weight",
    "dequantize_svdquant_w4a4_effective_weight",
    "fold_proj_down_for_raw_branch",
    "is_publishable_svdquant_gptq_state",
    "load_activation_sample_refs",
    "merge_activation_stats",
    "quantize_linear_weight_to_calibrated_natural_svdquant",
    "quantize_activation_w4_signed",
    "quantize_activation_w4_unsigned",
    "quantize_linear_weight_grouped_signed_int4_gptq",
    "quantize_linear_weight_to_gptq_natural_svdquant",
    "quantize_linear_weight_to_natural_svdquant",
    "reference_svdquant_w4a4_linear",
    "reference_svdquant_w4a4_linear_runtime",
    "reduce_activation_samples_from_safetensors",
    "solve_lowrank_residual_branch",
    "solve_lowrank_output_error_branch",
    "solve_smooth_factor",
    "summarize_activation_stats_map",
    "transform_gptq_hessian_input_basis",
    "unfold_proj_down_for_post_smoothing_branch",
]
